"""
Caption generator for the Remotion ad system.
Input:  a words.json  [{start,end,word}, ...]  (seconds, on the FINAL cut timeline)
Output: captionsData.ts  for Remotion (frames @ fps, scaled by /speed), with auto keyword colour.

Heuristic grouping: short punchy lines (<= MAX_WORDS / MAX_CHARS), breaking on sentence
punctuation and on pauses > GAP. One keyword per line is coloured orange (longest non-stopword,
numbers always highlighted).

Usage:
  python gen_captions.py <words.json> [--speed 1.1] [--fps 30] [--out path.ts]
"""
import json, sys, re, argparse

ORANGE = "#E8762D"
WHITE = "#FFFFFF"
MAX_WORDS = 4
MAX_CHARS = 22
GAP = 0.45            # seconds of silence that forces a new caption line
STOP = set("a an the and or but to of in on at is it's its for with you your we our i my so as be are was that this if no not don't can't will just".upper().split())

def is_num(w):
    return bool(re.search(r"\d", w))

def pick_keyword(words):
    # numbers win; else the longest word that isn't a stopword; else the longest
    nums = [w for w in words if is_num(w)]
    if nums:
        return max(nums, key=len)
    cands = [w for w in words if re.sub(r"[^A-Za-z']", "", w).upper() not in STOP and len(re.sub(r"[^A-Za-z]", "", w)) >= 4]
    pool = cands if cands else words
    return max(pool, key=lambda w: len(re.sub(r"[^A-Za-z0-9]", "", w)))

def group(words):
    lines, cur = [], []
    for i, w in enumerate(words):
        if cur:
            prev = cur[-1]
            gap = w["start"] - prev["end"]
            line_txt = " ".join(x["word"] for x in cur)
            ends_sentence = re.search(r"[.!?]$", prev["word"])
            if ends_sentence or gap > GAP or len(cur) >= MAX_WORDS or len(line_txt) >= MAX_CHARS:
                lines.append(cur); cur = []
        cur.append(w)
    if cur:
        lines.append(cur)
    return lines

def build(words, speed, fps):
    """PROGRESSIVE SENTENCE: group words into short one-line sentences; within each, every word
    appears (pops in) at the moment it's spoken, accumulating into the full line. One keyword/line
    is coloured orange. Each cap: {from, dur, words:[{t, c, rel}]} where rel = frames-after-`from`
    that the word appears."""
    caps = []
    lines = group(words)
    for li, ln in enumerate(lines):
        raw = [w["word"] for w in ln]
        key = pick_keyword(raw)
        frm = round(ln[0]["start"] / speed * fps)
        # hold the finished line until the next line starts (last line lingers a beat)
        if li + 1 < len(lines):
            nxt = round(lines[li + 1][0]["start"] / speed * fps)
        else:
            nxt = round((ln[-1]["end"] + 0.4) / speed * fps)
        dur = max(6, nxt - frm)
        wlist = []
        for w in ln:
            rel = max(0, round(w["start"] / speed * fps) - frm)
            wlist.append({"t": w["word"].upper(), "c": ORANGE if w["word"] == key else WHITE, "rel": rel})
        caps.append({"from": frm, "dur": dur, "words": wlist})
    return caps

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("words")
    ap.add_argument("--speed", type=float, default=1.1)
    ap.add_argument("--fps", type=int, default=30)
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    words = json.load(open(a.words, encoding="utf-8"))
    caps = build(words, a.speed, a.fps)
    ts = "// auto-generated by gen_captions.py (progressive word-by-word sentences)\n"
    ts += "export type CapWord = { t: string; c: string; rel: number };\n"
    ts += "export type Cap = { from: number; dur: number; words: CapWord[] };\n"
    ts += "export const CAPTIONS: Cap[] = " + json.dumps(caps, ensure_ascii=False) + ";\n"
    if a.out:
        open(a.out, "w", encoding="utf-8").write(ts)
        print("wrote", a.out)
    print(f"{len(caps)} caption lines. Preview:")
    for c in caps[:16]:
        print(f"  f{c['from']:>4}  " + " ".join(w["t"] for w in c["words"]) +
              "   [key: " + ",".join(w["t"] for w in c["words"] if w["c"] == ORANGE) + "]")

if __name__ == "__main__":
    main()
